a=input("enter a number a:")
b=input("enter a number b:")
print("the value of",a,"+",b,"is:",int(a)+int(b))
print("the value of",a,"-",b,"is:",int(a)-int(b))
print("the value of",a,"*",b,"is:",int(a)*int(b))
print("the value of",a,"/",b,"is:",int(a)/int(b))
print("the value of",a,"%",b,"is:",int(a)%int(b))
print("the value of",a,"//",b,"is:",int(a)//int(b))
print("the value of",a,"**",b,"is:",int(a)**int(b)) 